# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. These parameters are retrieved using config::get() of
# the config R package <https://rstudio.github.io/config/>.
#
# This file is meant to be adapted based on your needs: feel free to add parameters either in the
# default (applied to all tags) or for each tag separately (overwrite default). It is recommended to
# specify all parameters used, even if you use the default value.
#
# You can check the documentation of each function to learn what each of these parameters are doing
# as well as reading https://raphaelnussbaumer.com/GeoPressureManual/geopressuretemplate-workflow.html

default:
  tag_create: # ?tag_create()
    # crop_start: NULL # Generally set at the tag level
    # crop_end: NULL
  tag_label: # ? tag_label()
    warning_flight_duration: 1 # hours
    warning_stap_duration: 1 # hours
  tag_set_map: # ?tag_set_map()
    extent: [95, 120, 9, 40] # [W, E, S, N]
    scale: 8 # 1 (min) -> 1° ; 2 -> 0.5° ; 5 -> 0.25° ; 10 (max) -> 0.1°
    include_stap_id: NULL # default, take all
    include_min_duration: 0 # in hours
  geopressure_map: # ?geopressure_map()
    max_sample: 250
    margin: 10 # in m
    sd: 0.85
    thr_mask: 0.9
    log_linear_pooling_weight: !expr \(n) 2*log(n)/n
  twilight_create: # ?twilight_create()
    # twl_thr: NULL
    # twl_offset: NULL # in hours
  graph_create: # ?graph_create()
    thr_likelihood: 0.99
    thr_gs: 100 # km/h
    # likelihood: NULL # Best to leave NULL.
  graph_add_wind:
    thr_as: 80 # km/h
  graph_set_movement: # ?graph_set_movement()
    type: "as" # modify manually to "as" when you have downloaded wind data
    # method: "gamma"
    # shape: 7 # only for gamma
    # scale: 7
    # location: 40 # only for logistic
    # low_speed_fix: 15 # km/h
    # zero_speed_ratio: 1
  graph_simulation: # ?graph_simulation()
    nj: 10
  bird_create:
    scientific_name: "Calliope calliope"
  pressurepath_create: # ?pressurepath_create()
    variable: ["altitude", "surface_pressure"]
    era5_dataset: "single-levels"
    # solar_dep: 0
  geopressuretemplate: # ?geopressuretemplate()
    likelihood: ["map_pressure"]
    outputs: ["marginal", "most_likely", "simulation"]
    pressurepath: ["most_likely"] # "geopressureviz"

5D6:
  tag_create:
    crop_end: "2022-05-30"
  tag_set_map:
    known:
      stap_id: [1, -1]
      known_lon: 101.722533
      known_lat: 37.04525798

5D7:
  tag_create:
    crop_end: "2022-05-29"
  tag_set_map:
    known:
      stap_id: [1, -1]
      known_lon: 101.722533
      known_lat: 37.04525798

5D8:
  tag_create:
    crop_end: "2022-05-29"
  tag_set_map:
    known:
      stap_id: [1, -1]
      known_lon: 101.751121
      known_lat: 37.00182899

5E5:
  tag_create:
    crop_end: "2022-05-29"
  tag_set_map:
    known:
      stap_id: [1, -1]
      known_lon: 101.725552
      known_lat: 37.044269

5E7:
  tag_create:
    crop_end: "2022-05-30"
  tag_set_map:
    known:
      stap_id: [1, -1]
      known_lon: 101.724188
      known_lat: 37.04428903

56C:
  tag_create:
    crop_end: "2022-06-06"
  tag_set_map:
    known:
      stap_id: [1, -1]
      known_lon: 101.585549
      known_lat: 37.01987498

5CF:
  tag_create:
    crop_end: "2022-06-02"
  tag_set_map: # ?tag_set_map()
    scale: 5
    extent: [88, 116, 14, 63] # [W, E, S, N]
    known:
      stap_id: [1, -1]
      known_lon: 88.97598
      known_lat: 62.28616
  graph_create: # ?graph_create()
    thr_likelihood: 0.9
    thr_gs: 90 # km/h
