#library(devtools)
#devtools::install_github("Rafnuss/GeoPressureR")
#devtools::install()

library(GeoPressureR)
# Only used for some visualization. The code to compute the light position is included in `GeoPressureR`
library(GeoLocTools)
setupGeolocation()
# ERA5 data download library
library(ecmwfr)
# Graph library
library(igraph)
# Plotting library
library(ggplot2)
library(gridExtra)
library(plotly)
library(RColorBrewer)
# Interactif figure library
library(leaflet)
library(leaflet.extras)
#for 1-pressure
library(GeoPressureR)
library(leaflet)
library(leaflet.providers)
library(leaflet.extras)
library(ggplot2)
library(plotly)
library(RColorBrewer)
library(dplyr)
library(raster)
library(readxl)
#for 3-static
library(GeoPressureR)
library(leaflet)
library(leaflet.providers)
library(leaflet.extras)
library(ggplot2)
library(plotly)
library(RColorBrewer)
library(raster)
library(dplyr)
library(readxl)
#for 4-basic
library(GeoPressureR)
library(leaflet)
library(leaflet.extras)
library(raster)
library(igraph)
library(mapview)
library(htmlwidgets)
library(webshot)
#for 5-wind
library(GeoPressureR)
library(leaflet)
library(leaflet.extras)
library(raster)
library(igraph)
